// <auto-generated />
using System;
using System.Collections.Generic;
using CryptoOnRamp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoOnRamp.DAL.Migrations;

[DbContext(typeof(ApplicationContext))]
[Migration("20251003142209_AddDefaultLanguageToUsers3")]
partial class AddDefaultLanguageToUsers3
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "8.0.20")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.CheckoutSessionDb", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ExternalId")
                    .HasColumnType("text");

                b.Property<string>("PartnerContext")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PaymentMethod")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Ramp")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("TransactionId")
                    .HasColumnType("integer");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("TransactionId");

                b.ToTable("CheckoutSessions", "public");
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.FeeSchemeDb", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<decimal>("Percent")
                    .HasColumnType("numeric");

                b.Property<int?>("TargetUserId")
                    .HasColumnType("integer");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("UpdatedByUserId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("FeeSchemes", "public");
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.PayoutDb", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Amount")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatetAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CreatetBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("ToWallet")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("TransactionId")
                    .HasColumnType("integer");

                b.Property<string>("TxHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("TransactionId");

                b.ToTable("Payouts", "public");
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.SessionDb", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("ActivityAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Dictionary<string, string>>("Claims")
                    .IsRequired()
                    .HasColumnType("hstore");

                b.Property<DateTime>("ExpiredAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long>("Nonce")
                    .HasColumnType("bigint");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Sessions", "public");
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.TransactionDb", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<decimal>("AgentFee")
                    .HasColumnType("numeric");

                b.Property<decimal>("AgentPercent")
                    .HasColumnType("numeric");

                b.Property<string>("ExternalId")
                    .HasColumnType("text");

                b.Property<decimal>("FiatAmount")
                    .HasColumnType("numeric");

                b.Property<string>("FiatCurrency")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("NetPayout")
                    .HasColumnType("numeric");

                b.Property<string>("Provider")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("SuperAgentFee")
                    .HasColumnType("numeric");

                b.Property<decimal>("SuperAgentPercent")
                    .HasColumnType("numeric");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("TxHash")
                    .HasColumnType("text");

                b.Property<string>("UniquePrivateKey")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("UniqueWalletAddress")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("UserId")
                    .HasColumnType("integer");

                b.Property<string>("UserWallet")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Transactions", "public");
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.UserDb", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Country")
                    .HasColumnType("text");

                b.Property<DateTime?>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int?>("CreatedById")
                    .HasColumnType("integer");

                b.Property<string>("Email")
                    .HasColumnType("text")
                    .HasColumnName("Email");

                b.Property<bool?>("EmailConfirmed")
                    .HasColumnType("boolean");

                b.Property<bool?>("IsVerified")
                    .HasColumnType("boolean");

                b.Property<string>("Language")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("text")
                    .HasDefaultValue("English");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.Property<string>("PasswordHash")
                    .HasColumnType("text")
                    .HasColumnName("PasswordHash");

                b.Property<string>("PasswordResetKey")
                    .HasColumnType("text");

                b.Property<string>("Phone")
                    .HasColumnType("text");

                b.Property<string>("RegistrationStep")
                    .HasColumnType("text");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<long?>("TelegramId")
                    .HasColumnType("bigint");

                b.Property<string>("UsdcWallet")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Users", "public");
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.CheckoutSessionDb", b =>
            {
                b.HasOne("CryptoOnRamp.DAL.Models.TransactionDb", "Transaction")
                    .WithMany("CheckoutSessions")
                    .HasForeignKey("TransactionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Transaction");
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.PayoutDb", b =>
            {
                b.HasOne("CryptoOnRamp.DAL.Models.TransactionDb", "Transaction")
                    .WithMany("Payouts")
                    .HasForeignKey("TransactionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Transaction");
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.TransactionDb", b =>
            {
                b.HasOne("CryptoOnRamp.DAL.Models.UserDb", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("CryptoOnRamp.DAL.Models.TransactionDb", b =>
            {
                b.Navigation("CheckoutSessions");

                b.Navigation("Payouts");
            });
#pragma warning restore 612, 618
    }
}
